apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
  labels:
    app: mongodb
    name: fleetman-mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      name: db
      targetPort: 27017
  selector:
      app: fleetman-mongodb
    
