apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:         #This is main component of the service and helps it to route the requests to the correct pod.
    app: position-tracker
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

