apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: position-tracker
  name: position-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: position-tracker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: position-tracker
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-position-tracker:release3
        name: k8s-fleetman-position-tracker
        env: 
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice 
        resources: {}
status: {}
