apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: position-simulator
  name: position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-simulator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: position-simulator
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-position-simulator:release2
        name: k8s-fleetman-position-simulator
        env: 
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice 
        resources: {}
status: {}
