apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:         #This is main component of the service and helps it to route the requests to the correct pod.
    app: webapp
    release: "1"
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort

