apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      release: "1"
  template:
    metadata:
      name: webapp-release-1
      labels:
        app: webapp
        release: "1"
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-webapp-angular:release2
        name: webapp
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
